output_dir_base: '~/temp_data/wa_donations'
urls:
  donations_api: 'https://data.wa.gov/api/views/kv7h-kjye/rows.csv'
  donations_api_params:
    accessType: 'DOWNLOAD'
    api_foundry: 'true'
    # election_year: '2020'
    # primary_general: 'General'
filenames:
  pdc_api_token: "pdc_api_token.txt"
  donations_raw: "donations_raw.csv"
  donations_prepped: "donations_prepped.csv"
  
    
